name = "MultiPeriodDistOPF"
uuid = "de199323-92ca-4973-a48c-91e4c357c7e5"
authors = ["Aryan Ritwajeet Jha <aryan.r.jha@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
