clear all;
clc;

[DSSStartOK, DSSObj, DSSText] = DSSStartup;

if DSSStartOK
    

   

DSSObj.AllowForms = false;    


DSSText.Command = 'Set DataPath = C:\Users\rjha\Dropbox\730nodesystem\OpenDSS730node';

DSSText.Command = 'compile singlephase730.dss';  

    
% load busnamematlab.txt;
% busname = busnamematlab;

DSSCircuit      = DSSObj.ActiveCircuit;
DSSSolution     = DSSCircuit.Solution;
% DSSText.Command = 'set defaultbasefreq=50';
DSSSolution.Solve;                          %% solving the circuit without PV
Buses=DSSCircuit.Allbusnames;               %% knowing all the buses in the system
DSSCircuit.SetActiveElement('Vsource.SOURCE');                  %% power generated by source
Power_subsopend = -1*(DSSCircuit.ActivecktElement.Powers);
Vallnodes = DSSCircuit.AllBusVmagPU;
    

Buses1=str2double(Buses);

%% Voltage as per ascending node number

% bus_voltage = [busname Vallnodes'];         %% busname and corresponding volatge
% Vasced = sort(busname);                     %% sorting the bus name in ascending order
% VoltOpenDSS = [];
% for i = 1:size(Vasced,1)
% indx = find(i ==bus_voltage(:,1));
% Vo = bus_voltage(indx,2);
% VoltOpenDSS = [VoltOpenDSS Vo];
% end


          a = 'DSS start properly';
else
    
    a = 'DSS did not start properly';
    disp(a)
end

