# Ipopt vs FilterDDP (diagonal Hessian) on identical problems, one row per
# (system, T). FilterDDP is scored only at the first iterate that is primal
# feasible to 1e-6 and within 0.5% of the already-computed Ipopt objective.
# Strict-convergence tails remain in raw logs but are deliberately not reported.
#
#   julia --startup-file=no --project=envs/ddp2026 \
#         ddp/examples/power_system/summarize_matched_race.jl <race_dir>
#
# Writes <race_dir>/matched_race.csv and prints the table.

using Printf

race = ARGS[1]
const REPO = normpath(joinpath(@__DIR__, "..", "..", ".."))
logdir = joinpath(race, "logs")

kv(s) = Dict(m.captures[1] => m.captures[2] for m in eachmatch(r"(\w+)=(\S+)", s))

function ipopt_row(sys, T)
    p = joinpath(logdir, "ipopt_$(sys)_T$(T).log")
    isfile(p) || return nothing
    txt = read(p, String)
    m = match(r"CENTRAL_IPOPT [^\n]*", txt)
    m === nothing && return (status = occursin("PIPELINE_STEP_OK", txt) ? "CRASHED" : "RUNNING",
                             iters = -1, solve = NaN, obj = NaN, gamma = NaN)
    d = kv(m.match)
    return (status = d["status"], iters = parse(Int, d["iterations"]),
            solve = parse(Float64, d["solve_time_s"]), obj = parse(Float64, d["objective"]),
            gamma = parse(Float64, get(d, "gamma", "NaN")))
end

function fddp_row(sys, T)
    p = joinpath(logdir, "fddp_diag_$(sys)_T$(T).log")
    isfile(p) || return nothing
    txt = read(p, String)
    m = match(r"solve complete: ([\d.]+) s, iterations=(\d+), status=(\d+)", txt)
    o = match(r"FilterDDP objective=([-\d.eE+]+)", txt)
    g = match(r"TERMINAL_SOC soft=\d gamma=([-\d.eE+]+)", txt)
    fb = match(r"factor_backed=(\d)", txt)
    base = (gamma = g === nothing ? NaN : parse(Float64, g.captures[1]),
            fb = fb === nothing ? 0 : parse(Int, fb.captures[1]))
    m === nothing && return (status = occursin("PIPELINE_STEP_OK", txt) ? "CRASHED" : "RUNNING",
                             iters = -1, wall = NaN, obj = NaN, base...)
    return (status = m.captures[3] == "0" ? "OK" : "FAIL" * m.captures[3],
            iters = parse(Int, m.captures[2]), wall = parse(Float64, m.captures[1]),
            obj = o === nothing ? NaN : parse(Float64, o.captures[1]), base...)
end

old = Dict{Tuple{String,Int},Tuple{Float64,Int}}()
oldcsv = joinpath(REPO, "ddp", "results", "centralized_ipopt", "centralized_ipopt_timing.csv")
if isfile(oldcsv)
    lines = readlines(oldcsv)
    hdr = [strip(h, '"') for h in split(lines[1], ',')]
    ix(n) = findfirst(==(n), hdr)
    for l in lines[2:end]
        f = [strip(x, '"') for x in split(l, ',')]
        old[(f[ix("system")], parse(Int, f[ix("T")]))] =
            (parse(Float64, f[ix("ipopt_reported_s")]), parse(Int, f[ix("iterations")]))
    end
end

# Generated by near_opt_from_logs.jl immediately before this report. One row is
# retained for the standing P=1e-6 criterion.
near = Dict{Tuple{String,Int},NamedTuple}()
nearcsv = joinpath(race, "near_opt.csv")
if isfile(nearcsv)
    lines = readlines(nearcsv)
    hdr = split(lines[1], ',')
    ix(n) = findfirst(==(n), hdr)
    for l in lines[2:end]
        f = split(l, ',')
        parse(Float64, f[ix("P")]) == 1e-6 || continue
        near[(f[ix("system")], parse(Int, f[ix("T")]))] =
            (iters = parse(Int, f[ix("near_opt_iteration")]),
             time = parse(Float64, f[ix("near_opt_time_s")]),
             obj = parse(Float64, f[ix("near_opt_objective")]),
             gap = parse(Float64, f[ix("near_opt_rel_gap")]))
    end
end

keys_ = Tuple{String,Int}[]
for f in (isdir(logdir) ? readdir(logdir) : String[])
    m = match(r"^(?:ipopt|fddp_diag)_(\w+?)_T(\d+)\.log$", f)
    m === nothing || push!(keys_, (m.captures[1], parse(Int, m.captures[2])))
end
sysorder = Dict("ieee123C_1ph" => 1, "ieee2522C_1ph" => 2, "large10kC_1ph" => 3)
sort!(unique!(keys_), by = k -> (get(sysorder, k[1], 9), k[2]))

f1(x) = isnan(x) ? "--" : @sprintf("%.1f", x)

# Median cores used by OTHER processes during a run (sample_background_load.jl).
# Runs shorter than one 15 s sample fall back to the pre-run QUIET_WAIT reading.
function background(csv, log)
    vals = Float64[]
    if isfile(csv)
        for l in Iterators.drop(eachline(csv), 1)
            f = split(l, ',')
            length(f) >= 2 && (v = tryparse(Float64, f[2]); v === nothing || push!(vals, v))
        end
    end
    if isempty(vals) && isfile(log)
        m = match(r"QUIET_WAIT waited_s=\S+ other_cores=([\d.]+)", read(log, String))
        m === nothing || push!(vals, parse(Float64, m.captures[1]))
    end
    isempty(vals) && return NaN
    sort!(vals)
    return vals[cld(length(vals), 2)]
end
const BUSY = 1.5
bgstr(x) = isnan(x) ? "--" : @sprintf("%.1f%s", x, x > BUSY ? "*" : "")

open(joinpath(race, "matched_race.csv"), "w") do io
    println(io, "system,T,gamma,ipopt_status,ipopt_iterations,ipopt_solve_s,ipopt_objective,filterddp_near_status,filterddp_near_iteration,filterddp_near_s,filterddp_near_objective,factor_backed,near_obj_rel_gap,near_over_ipopt,oldfamily_ipopt_s,oldfamily_iterations,ipopt_background_cores,filterddp_background_cores")
    println("=" ^ 118)
    println("IDENTICAL PROBLEMS: centralized Ipopt vs FilterDDP time to near-optimality")
    println("periodic profile, C_B = 1e-3, soft terminal SOC with per-system gamma (terminal_soc_penalty.jl)")
    println("FilterDDP stop: primal infeasibility <= 1e-6 and objective within 0.5% of Ipopt; strict tail excluded")
    println("=" ^ 118)
    @printf("%-14s %4s | %-15s %5s %9s %5s | %-7s %5s %9s %5s | %9s %9s | %15s\n",
            "system", "T", "ipopt", "iters", "ipopt s", "bg", "near", "iter", "near s", "bg",
            "obj gap", "near/ip", "old-family ref")
    println("-" ^ 118)
    for (sys, T) in keys_
        I = ipopt_row(sys, T); D = fddp_row(sys, T); N = get(near, (sys, T), nothing)
        rel = N === nothing ? NaN : N.gap
        ratio = (I !== nothing && N !== nothing && !isnan(I.solve)) ? N.time / I.solve : NaN
        o = get(old, (sys, T), (NaN, -1))
        gam = I !== nothing ? I.gamma : (D !== nothing ? D.gamma : NaN)
        bgI = background(joinpath(logdir, "load_ipopt_$(sys)_T$(T).csv"), joinpath(logdir, "ipopt_$(sys)_T$(T).log"))
        bgD = background(joinpath(logdir, "load_fddp_$(sys)_T$(T).csv"), joinpath(logdir, "fddp_diag_$(sys)_T$(T).log"))
        @printf(io, "%s,%d,%.6e,%s,%d,%.3f,%.12g,%s,%d,%.3f,%.12g,%d,%.3e,%.4f,%.3f,%d,%.3f,%.3f\n",
                sys, T, gam,
                I === nothing ? "" : I.status, I === nothing ? -1 : I.iters,
                I === nothing ? NaN : I.solve, I === nothing ? NaN : I.obj,
                N === nothing ? "" : "NEAR_OPT", N === nothing ? -1 : N.iters,
                N === nothing ? NaN : N.time, N === nothing ? NaN : N.obj,
                D === nothing ? 0 : D.fb, rel, ratio, o[1], o[2], bgI, bgD)
        @printf("%-14s %4d | %-15s %5s %9s %5s | %-7s %5s %9s %5s | %9s %9s | %15s\n",
                sys, T,
                I === nothing ? "--" : first(I.status, 15),
                I === nothing || I.iters < 0 ? "--" : string(I.iters),
                I === nothing ? "--" : f1(I.solve), bgstr(bgI),
                N === nothing ? "--" : "NEAR_OPT",
                N === nothing || N.iters < 0 ? "--" : string(N.iters),
                N === nothing ? "--" : f1(N.time), bgstr(bgD),
                isnan(rel) ? "--" : @sprintf("%.1e", rel),
                isnan(ratio) ? "--" : @sprintf("%.2fx", ratio),
                isnan(o[1]) ? "--" : @sprintf("%.1f s/%d it", o[1], o[2]))
    end
end
println("-" ^ 118)
println("ipopt s = Ipopt solve time. near s = FilterDDP time to the approved near-optimal criterion.")
println("near/ip < 1.00x means FilterDDP reaches that criterion faster than Ipopt completes.")
println("obj gap = |Ipopt - FilterDDP| / |Ipopt| at the qualifying FilterDDP iterate.")
println("bg = median cores used by OTHER processes during the run (idle floor ~0.4); * = above 1.5, timing suspect.")
println("old-family ref = the paper's centralized sweep (C_B ~ 8.8e-8, old sampling, free terminal SOC):")
println("  a DIFFERENT problem, shown only to locate the knee it exhibited.")
