"""Summarize kkt_evolution_analysis.jl output: which KKT blocks move between
FilterDDP iterations, by how much, and when.

Writes ddp/results/kkt_evolution/SUMMARY.md and a figure per system
(figures/kkt_evolution_<system>.png): the relative change of each block
between consecutive captures, over iterations, with the barrier parameter.

    python ddp/examples/power_system/summarize_kkt_evolution.py
"""
import csv
import glob
import os
import statistics as st
from collections import defaultdict

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "..", "results", "kkt_evolution"))
LABEL = {"ieee123C_1ph": "ieee123", "ieee2522C_1ph": "med2522", "large10kC_1ph": "large10k"}
MAIN = ["H.barrier", "H.Vxx", "H.rest", "J"]
JGROUPS = ["J:Pbal", "J:Qbal", "J:vdrop", "J:SOCP", "J:rootV", "J:energy"]
HGROUPS = ["ps", "P", "Q", "v", "ell", "pb", "qnorm", "soc_slack", "energy_slack"]


def f(x):
    try:
        return float(x)
    except ValueError:
        return float("nan")


def q(xs, p):
    xs = sorted(x for x in xs if x == x)
    return xs[min(len(xs) - 1, int(p * len(xs)))] if xs else float("nan")


def fmt(x):
    if x != x:
        return "--"
    if x == 0:
        return "0"
    return f"{x:.2g}" if abs(x) < 0.01 or abs(x) >= 100 else f"{x:.2f}"


lines = ["# KKT matrix evolution between FilterDDP iterations", "",
         "Generated by `summarize_kkt_evolution.py` from `kkt_evolution_*.csv`",
         "(`kkt_evolution_analysis.jl`, `run_kkt_evolution.sh`). Relative change is",
         "`||new - old||_F / ||old||_F` between consecutive captures of the same stage,",
         "over all stages and iteration pairs; `share` is the block's share of",
         "`||K_new - K_old||_F^2`; the last column is the median, over iteration",
         "pairs, of the largest factor by which any single entry of the block changed.", ""]

for path in sorted(glob.glob(os.path.join(OUT, "kkt_evolution_*.csv"))):
    rows = list(csv.DictReader(open(path)))
    if not rows:
        continue
    system = rows[0]["system"]
    name = LABEL.get(system, system)
    gap = st.median(int(r["iter"]) - int(r["iter_prev"]) for r in rows if r["block"] == "K")
    by = defaultdict(list)
    for r in rows:
        by[r["block"]].append(r)
    iters = sorted({int(r["iter"]) for r in rows})
    lines += [f"## {name} (T=6, captures every {gap:g} iteration(s), iterations "
              f"{iters[0]}-{iters[-1]})", "",
              "| block | median change | 90th pct | max | median share of dK | max factor per entry (median) |",
              "|---|---:|---:|---:|---:|---:|"]
    for b in ["K"] + MAIN + [f"H.barrier:{g}" for g in HGROUPS] + \
             [f"H.diag:{g}" for g in ("P", "Q", "pb")] + JGROUPS:
        if b not in by:
            continue
        rc = [f(r["rel_change"]) for r in by[b]]
        sh = [f(r["share_dK2"]) for r in by[b]]
        ml = [f(r["max_log10"]) for r in by[b]]
        mlm = q(ml, 0.5)
        lines.append(f"| {b} | {fmt(q(rc, .5))} | {fmt(q(rc, .9))} | {fmt(max(x for x in rc if x == x))} "
                     f"| {fmt(q(sh, .5))} | {fmt(10 ** mlm) if mlm == mlm else '--'} |")
    lines.append("")

    # Figure: stage-median relative change per iteration, per main block, with mu.
    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    for b, col in zip(MAIN + ["J:SOCP"], ["C3", "C2", "C1", "C0", "C4"]):
        per = defaultdict(list)
        for r in by.get(b, []):
            per[int(r["iter"])].append(f(r["rel_change"]))
        xs = sorted(per)
        ys = [max(st.median(per[x]), 1e-12) for x in xs]
        if xs:
            ax.semilogy(xs, ys, color=col, lw=1.4, label=b)
    ax.set_xlabel("iteration")
    ax.set_ylabel("relative change vs previous capture")
    ax.set_ylim(1e-8, 1e2)
    mu = sorted({(int(r["iter"]), f(r["mu"])) for r in by["K"]})
    ax2 = ax.twinx()
    ax2.semilogy([m[0] for m in mu], [m[1] for m in mu], "k--", lw=1, label="barrier μ")
    ax2.set_ylabel("barrier parameter μ")
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=7, loc="lower left", ncol=2)
    ax.set_title(f"{name}: stage KKT change between iterations (median over stages)", fontsize=9)
    fig.tight_layout()
    figdir = os.path.join(OUT, "figures")
    os.makedirs(figdir, exist_ok=True)
    fig.savefig(os.path.join(figdir, f"kkt_evolution_{name}.png"), dpi=160)
    plt.close(fig)

open(os.path.join(OUT, "SUMMARY.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("\n".join(lines))
